name = "sesap-indexing"
main = "src/index.ts"
compatibility_date = "2024-12-18"

[dev]
port = 8789
inspector_port = 9231

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "AI_NEURON_LIMITER"
class_name = "AiNeuronLimiter"
script_name = "sesap-processing"

[[r2_buckets]]
binding = "SESAP_BUCKET"
bucket_name = "<YOUR_R2_BUCKET_NAME>"

[[kv_namespaces]]
binding = "SESAP_KV"
id = "<YOUR_KV_NAMESPACE_ID>"
preview_id = "<YOUR_KV_PREVIEW_ID>"

[vars]
ENVIRONMENT = "development"
