#!/usr/bin/env bash
set -euo pipefail

# Provisions per-worker wrangler.toml files for local development.
#
# Behavior:
#   1. For each worker, copy wrangler.example.toml -> wrangler.toml if missing.
#   2. Replace any remaining "<YOUR_...>" placeholders with valid-format
#      local-only stub values so `wrangler dev` (which defaults to local
#      mode in wrangler v3.40+) can start without contacting Cloudflare.
#
# Safety:
#   - wrangler.toml is gitignored, so this never affects committed state
#     or staging deployments (staging deploys use real values supplied
#     elsewhere — typically CI or a deploy machine).
#   - Substitution is idempotent: real values (anything not matching the
#     placeholder pattern) are left untouched on re-run.
#   - These stub values are local-only. Deploying with them will fail
#     against Cloudflare — which is the desired safety behavior.

WORKERS=(admin processing indexing showcase)

# Local-only stub values. Names/IDs must satisfy wrangler's format validators
# (R2 bucket: lowercase alphanumeric + hyphens, 3–63 chars; KV id: 32-char hex).
STUB_R2_BUCKET="sesap-local-dev"
STUB_KV_ID="0000000000000000000000000000000a"
STUB_KV_PREVIEW_ID="0000000000000000000000000000000b"

# Cross-platform sed -i (BSD/macOS vs GNU)
sed_inplace() {
  if sed --version >/dev/null 2>&1; then
    sed -i "$@"
  else
    sed -i '' "$@"
  fi
}

# Sentinel comment prepended to any file that received stub values, so CI can
# grep for it and refuse to deploy with stub IDs.
STUB_SENTINEL='# WRANGLER_STUB_DO_NOT_DEPLOY — replace KV/R2 ids before running `wrangler deploy`'

ensure_sentinel() {
  local file="$1"
  if ! grep -qF 'WRANGLER_STUB_DO_NOT_DEPLOY' "$file"; then
    # Prepend the sentinel as the first line.
    local tmp
    tmp="$(mktemp)"
    printf '%s\n' "$STUB_SENTINEL" > "$tmp"
    cat "$file" >> "$tmp"
    mv "$tmp" "$file"
  fi
}

fill_placeholders() {
  local file="$1"
  local replaced=0
  if grep -q '<YOUR_R2_BUCKET_NAME>' "$file"; then
    sed_inplace "s|<YOUR_R2_BUCKET_NAME>|${STUB_R2_BUCKET}|g" "$file"
    echo "    - filled <YOUR_R2_BUCKET_NAME> -> ${STUB_R2_BUCKET}"
    replaced=1
  fi
  if grep -q '<YOUR_KV_NAMESPACE_ID>' "$file"; then
    sed_inplace "s|<YOUR_KV_NAMESPACE_ID>|${STUB_KV_ID}|g" "$file"
    echo "    - filled <YOUR_KV_NAMESPACE_ID> -> ${STUB_KV_ID}"
    replaced=1
  fi
  if grep -q '<YOUR_KV_PREVIEW_ID>' "$file"; then
    sed_inplace "s|<YOUR_KV_PREVIEW_ID>|${STUB_KV_PREVIEW_ID}|g" "$file"
    echo "    - filled <YOUR_KV_PREVIEW_ID> -> ${STUB_KV_PREVIEW_ID}"
    replaced=1
  fi
  if [ "$replaced" -eq 1 ]; then
    ensure_sentinel "$file"
  fi
}

echo "Setting up wrangler.toml files for local development..."
echo ""

for worker in "${WORKERS[@]}"; do
  src="workers/$worker/wrangler.example.toml"
  dst="workers/$worker/wrangler.toml"

  if [ ! -f "$src" ]; then
    echo "  [error] Template not found: $src"
    continue
  fi

  if [ -f "$dst" ]; then
    echo "  [exists] $dst"
  else
    cp "$src" "$dst"
    echo "  [created] $dst from template"
  fi

  fill_placeholders "$dst"
done

# The showcase worker's wrangler.toml points `assets.directory` at
# workers/showcase/public/, which is normally generated by building the
# Next.js UI (`workers/showcase/ui` -> `out/` -> copied to ../public). For
# `wrangler dev` to start before the first build, ensure the directory exists.
SHOWCASE_PUBLIC="workers/showcase/public"
if [ ! -d "$SHOWCASE_PUBLIC" ]; then
  mkdir -p "$SHOWCASE_PUBLIC"
  # Wrangler's assets directory cannot be empty in some versions; drop a
  # placeholder so the dev server is happy until the UI is built.
  cat > "$SHOWCASE_PUBLIC/index.html" <<'HTML'
<!doctype html>
<title>SESAP showcase (dev placeholder)</title>
<p>In local dev, the showcase worker (port 8790) proxies UI requests to <code>next dev</code> on port 3000 via <code>NEXT_DEV_URL</code>. If you see this page, that proxy is unset and no static build has populated this directory; run <code>make dev</code>.</p>
HTML
  echo "  [created] $SHOWCASE_PUBLIC/ (placeholder for wrangler dev)"
else
  echo "  [exists] $SHOWCASE_PUBLIC/"
fi

echo ""
echo "Done."
echo ""
echo "Local development:  make dev"
echo "  Wrangler runs in local mode; R2/KV are simulated under .wrangler/state."
echo ""
echo "Before deploying:   replace stub values in each workers/*/wrangler.toml"
echo "  with real Cloudflare resource IDs:"
echo "    wrangler r2 bucket list"
echo "    wrangler kv namespace list"
