name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  python:
    name: Python lint and tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: llm_pipeline
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint
        run: ruff check .
      - name: Run tests
        run: pytest

  node:
    name: Node lint and tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: generator
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test
